# Generated by Django 6.0 on 2025-12-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
