# Generated by Django 6.0 on 2025-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_journalentry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='time',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='end_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='start_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
