# Generated by Django 6.0 on 2025-12-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('starter_code', models.TextField(default='<h1></h1>')),
                ('hint', models.TextField(blank=True)),
                ('validation_text', models.CharField(max_length=100)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.goal')),
            ],
        ),
    ]
